print(">>> Квадрат числа. <<<")
user_response = float(input("Введіть число: "))
print("Квадрат числа: ", user_response ** 2)
print()

print(">>> Середнє трьох чисел <<<")
user_response_1 = float(input("Введіть число 1: "))
user_response_2 = float(input("Введіть число 2: "))
user_response_3 = float(input("Введіть число 3: "))
print("Середнє: ", (user_response_1 + user_response_2 + user_response_3) / 3)
print()

print(">>> Перетворення хвилин у години <<<")
user_time = int(input("Введіть кількість хвилин: "))
print(user_time // 60, "годин", user_time % 60, "хвилин")
print()

print(">>> Розрахунок знижки <<<")
user_price = float(input("Введіть ціну: "))
user_disc = float(input("Введіть знижку (%): "))
print("Ціна зі знижкою: ", user_price * (100 - user_disc) / 100)
print()

print(">>> Остання цифра числа <<<")
user_response = int(input("Введіть число: "))
print("Остання цифра:", user_response % 10)
print()

print(">>> Периметр прямокутника <<<")
user_x = float(input("Введіть довжину: "))
user_y = float(input("Введіть ширину: "))
print("Периметр: ", (user_x + user_y) * 2)
print()

print(">>> Виведення числа в стовпчик <<<")
user_int = int(input("Введіть число: "))
print(user_int // 1000)
print(user_int % 1000 // 100)
print(user_int % 100 // 10)
print(user_int % 10)
