print(">>> Квадрат числа. <<<")
user_response = float(input("Введіть число: "))
print("Квадрат числа: ", user_response**2)
print()

print(">>> Середнє трьох чисел <<<")
user_response_1 = float(input("Введіть число 1: "))
user_response_2 = float(input("Введіть число 2: "))
user_response_3 = float(input("Введіть число 3: "))
print("Середнє: ", (user_response_1+user_response_2+user_response_3)/3)
print()

print(">>> Перетворення хвилин у години <<<")
user_response = int(input("Введіть кількість хвилин: "))
print(user_response//60, "годин", user_response%60, "хвилин")
print()

print(">>> Розрахунок знижки <<<")
user_response_1 = float(input("Введіть ціну: "))
user_response_2 = float(input("Введіть знижку (%): "))
print("Ціна зі знижкою: ", user_response_1*(100-user_response_2)/100)
print()

print(">>> Остання цифра числа <<<")
user_response = int(input("Введіть число: "))
print("Остання цифра:", user_response%10)
print()

print(">>> Периметр прямокутника <<<")
user_response_1 = float(input("Введіть довжину: "))
user_response_2 = float(input("Введіть ширину: "))
print("Периметр: ", (user_response_1+user_response_2)*2)
print()

print(">>> Виведення числа в стовпчик <<<")
user_response = int(input("Введіть число: "))
print(user_response//1000)
print(user_response%1000//100)
print(user_response%100//10)
print(user_response%10)
